"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](bright-black)\
$os\
$username\
[](bg:bright-red fg:bright-black)\
$directory\
[](fg:bright-red bg:green)\
$git_branch\
$git_status\
[](fg:green bg:bright-blue)\
$nix_shell\
$docker_context\
$c\
$rust\
$nodejs\
$java\
$kotlin\
$python\
$cpp\
$dotnet\
[](fg:bright-blue bg:blue)\
$docker_context\
[](fg:blue bg:purple)\
$time\
[ ](fg:purple)\
$line_break$character"""

[os]
disabled = false
style = "bg:bright-black fg:white"

[os.symbols]
Linux = "󰌽"
Gentoo = "󰣨"
Android = ""
Arch = "󰌽"
# Arch = "󰣇"

[username]
show_always = true
style_user = "bg:bright-black fg:white"
style_root = "bg:bright-black fg:white"
format = '[ $user ]($style)'

[directory]
style = "fg:black bg:bright-red"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Desktop" = "󰇄 "
"Downloads" = " "
"Pictures" = " "
"Projects" = "󰲋 "
"Games" = "󰊖 "

[git_branch]
symbol = ""
style = "bg:bright-blue"
format = '[[ $symbol $branch ](fg:black bg:green)]($style)'

[git_status]
style = "bg:bright-blue"
format = '[[($all_status$ahead_behind )](fg:black bg:green)]($style)'

[nodejs]
symbol = " "
style = "bg:bright-blue"
format = '[[ $symbol( $version) ](fg:black bg:bright-blue)]($style)'

[c]
symbol = " "
style = "bg:bright-blue"
format = '[[ $symbol( $version) ](fg:black bg:bright-blue)]($style)'

[rust]
symbol = " "
style = "bg:bright-blue"
format = '[[ $symbol( $version) ](fg:black bg:bright-blue)]($style)'

[java]
symbol = " "
style = "bg:bright-blue"
format = '[[ $symbol( $version) ](fg:black bg:bright-blue)]($style)'

[kotlin]
symbol = " "
style = "bg:bright-blue"
format = '[[ $symbol( $version) ](fg:black bg:bright-blue)]($style)'

[python]
symbol = " "
style = "bg:bright-blue"
format = '[[ $symbol( $version) ](fg:black bg:bright-blue)]($style)'

[cpp]
disabled = false
symbol = "󰙲 "
style = "bg:bright-blue"
format = '[[ $symbol( $version) ](fg:black bg:bright-blue)]($style)'

[dotnet]
symbol = "󰌛 "
style = "bg:bright-blue"
format = '[[ $symbol( $version) ](fg:black bg:bright-blue)]($style)'

[nix_shell]
disabled = true
symbol = " "
style = "bg:bright-blue"
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [[$symbol( $state) ](fg:black bg:bright-blue)]($style)'

[docker_context]
symbol = " "
style = "bg:bright-blue"
format = '[[ $symbol( $context) ](fg:black bg:bright-blue)]($style)'

[time]
disabled = false
time_format = "%I:%M %p"
style = "bg:bright-red"
format = '[[  $time ](fg:black bg:purple)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:magenta)'

